[package]
name = "cargo-mybin"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cargo-mylib = "0.1.0"

[patch.crates-io]
cargo-mylib = { git = "https://github.com/loloicci/cargo-mylib.git" }
